### ISSUE TITLE
DigitalOcean Mesosphere Dashboard gone

### ISSUE THREAD

**Issue by pplanel** [mesosphere/docker-mesos-marathon-screencast#3]
Where is the dashboard from DigitalOceans in mesosphere website? I've build the cluster with it but now is gone...

**Comment by ssk2** [comment]
It's back!

**Comment by huemans** [comment]
Hi all, Im not seeing the DO mesosphere dashboard either. I see posts that point to digitalocean.mesosphere.com but this redirects to Mesosphere home page. Is this project still alive?

**Comment by ssk2** [comment]
Hi @huemans - digitalocean.mesosphere.com has been deprecated now! We don't have a DigitalOcean provisioning tool at the moment unfortunately.

**Comment by hyperfocus1338** [comment]
What happened to it? Why is it deprecated?

**Comment by ssk2** [comment]
@hyperfocus1337 - our product has since evolved to become DCOS  (https://mesosphere.com/product/). We're still working on DigitalOcean integration!

**Comment by subfuzion** [comment]
:+1: Looking forward to parity with AWS!

**Comment by rfjohnso** [comment]
When can we expect DigitalOcean integration?!?  Looking forward to that!

**Comment by ssk2** [comment]
@rfjohnso - afraid it's not due anytime soon. We do have some interesting new products in the works that allow you to deploy onto DigitalOcean soon though!

**Comment by microstacks** [comment]
any update on digitalocean integration? could you elaborate on new products. We need to decided between AWS vs DigitalOcean for our services. DO is very cheap compared to AWS and would like to use mesosphere DCOS with DO. Please update ASAP.

**Comment by ssk2** [comment]
Hi @dupperinc - please drop a line to our sales team at sales@mesosphere.com if this is a product you're interested in!
